# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Event Sourcing Bundle
site_url: https://patchlevel.github.io/event-sourcing-bundle-docs/
repo_url: https://github.com/patchlevel/event-sourcing-bundle
repo_name: patchlevel/event-sourcing-bundle
edit_uri: edit/2.0.x/docs/pages/
docs_dir: pages

extra:
  meta:
    title: Event Sourcing Bundle
    description: An event sourcing bundle, complete with all the essential features, powered by the reliable Doctrine ecosystem and focused on developer experience.
    image: img/patchlevel-banner.png
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patchlevel
    - icon: fontawesome/solid/globe
      link: https://patchlevel.de
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/patchlevelhq
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/includes/links.md
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Basics:
    - Aggregate: aggregate.md
    - Events: events.md
    - Repository: repository.md
    - Store: store.md
    - Subscription: subscription.md
    - Event Bus:  event_bus.md
  - Advanced:
    - Normalizer: normalizer.md
    - Snapshots: snapshots.md
    - Upcasting: upcasting.md
    - Message Decorator: message_decorator.md
    - Time / Clock: clock.md
    - CLI: cli.md
